### ISSUE TITLE
Athame Usabillity

### ISSUE THREAD

**Issue by bakaschwarz** [geratheon/EnderOres#6]
For the sake of good usage i suggest a small counter which indicates the amount of mini pearls stored in the athame on the bottom right of the item icon.

Also, exists a limit to how many pearls can be stored? This should be indicated.

**Comment by geratheon** [comment]
Max pearl indicator: implemented. Pearl counter in icon: denied. (There are three different icons to indicate that. For precise values look at the tooltip!)
